use std::alloc::{alloc, dealloc, handle_alloc_error, Layout};

struct Node {
    next: *mut Node,
    value: i32,
}

struct Stack {
    head: *mut Node,
}

pred nodes(n: *mut Node; sum: int) =
    if n == null then
        sum == 0
    else
        n::Node(n; next, v) &*& nodes(next, ?rest_sum) &*& sum == v + rest_sum;

pred stack(s: *mut Stack; sum: int) =
    s::Stack(s; head) &*& nodes(head, sum);

#[requires(nodes(nodes, ?sum))]
#[ensures(nodes(nodes, sum) &*& result == sum)]
unsafe fn get_nodes_sum(nodes: *mut Node) -> i32 {
    let mut result = 0;

    if nodes != std::ptr::null_mut() {
        result = get_nodes_sum((*nodes).next);
        result += (*nodes).value;
    }

    result
}

impl Stack {
    #[ensures(stack(result, 0))]
    unsafe fn create() -> *mut Stack {
        let stack = alloc(Layout::new::<Stack>()) as *mut Stack;
        if stack.is_null() {
            handle_alloc_error(Layout::new::<Stack>());
        }
        // Allocate stack struct ownership
        create_stack(stack);
        (*stack).head = std::ptr::null_mut();

        stack
    }

    #[requires(stack(stack, ?sum))]
    #[ensures(stack(stack, sum) &*& result == (sum == 0))]
    unsafe fn is_empty(stack: *mut Stack) -> bool {
        let head = (*stack).head;

        let result = (*stack).head.is_null();

        result
    }

    #[requires(stack(stack, ?sum))]
    #[ensures(stack(stack, sum) &*& result == sum)]
    unsafe fn get_sum(stack: *mut Stack) -> i32 {
        let result = get_nodes_sum((*stack).head);

        result
    }

    #[requires(stack(stack, ?sum))]
    #[ensures(stack(stack, sum + value))]
    unsafe fn push(stack: *mut Stack, value: i32) {
        let n = alloc(Layout::new::<Node>()) as *mut Node;
        if n.is_null() {
            handle_alloc_error(Layout::new::<Node>());
        }
        // allocate node memory ownership
        create_node(n, std::ptr::null_mut(), value);
        (*n).next = (*stack).head;
        (*n).value = value;
        (*stack).head = n;
    }

    #[requires(stack(stack, ?sum) &*& sum != 0)]
    #[ensures(stack(stack, sum - result))]
    unsafe fn pop(stack: *mut Stack) -> i32 {
        let head = (*stack).head;

        let result = (*head).value;
        (*stack).head = (*head).next;
        // deallocate node ownership
        destroy_node(head);

        result
    }

    #[requires(stack(stack, ?sum) &*& n >= 0)]
    #[ensures(stack(stack, ?new_sum))]
    unsafe fn popn(stack: *mut Stack, n: i32) {
        let mut i = 0;
        #[invariant(stack(stack, ?cur_sum) &*& 0 <= i &*& i <= n)]
        loop {
            if i == n {
                break;
            }
            Stack::pop(stack);
            i += 1;
        }
    }

    #[requires(stack(stack, ?sum))]
    #[ensures(true)]
    unsafe fn dispose(stack: *mut Stack) {
        let mut n = (*stack).head;
        #[invariant(nodes(n, ?cur_sum))]
        loop {
            if n == std::ptr::null_mut() {
                break;
            }

            let next = (*n).next;
            destroy_node(n);
            n = next;
        }
        destroy_stack(stack);
    }
}

// Constructors and destructors for points-to predicates

predicate_ctor create_node(n: *mut Node, next: *mut Node, value: int)() =
    n::Node(n; next, value);

predicate_ctor destroy_node(n: *mut Node)() =
    n::Node(n; ?next, ?value);

predicate_ctor create_stack(s: *mut Stack)() =
    s::Stack(s; std::ptr::null_mut());

predicate_ctor destroy_stack(s: *mut Stack)() =
    s::Stack(s; ?head);

// Points-to predicates generated by VeriFast from struct fields

predicate n::Node(n: *mut Node; next: *mut Node, value: int) =
    n != null &*&
    pointer(n) &*&
    n->next |-> next &*& n->value |-> value;

predicate s::Stack(s: *mut Stack; head: *mut Node) =
    s != null &*&
    pointer(s) &*&
    s->head |-> head;

// pointers as opaque predicate to reflect raw pointer heap ownership

predicate pointer(p: *mut u8) = p != null;

// main unchanged

fn main() {
    unsafe {
        let s = Stack::create();
        Stack::push(s, 10);
        Stack::push(s, 20);
        Stack::pop(s);
        Stack::pop(s);
        Stack::dispose(s);
    }
}